name: Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: pcov

      - name: Create database
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS laravel_ci;'

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.ci .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Execute tests
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: laravel_ci
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: root
        run: |
          php artisan migrate:fresh --seed
          php artisan test --coverage
